spring:
  application:
    name: ocr-api
  data:
    mongodb:
      uri:
  cloud:
    aws:
      region:
        static:
      sqs:
        enabled: true
        endpoint: https://sqs.us-east-1.amazonaws.com
        region: us-east-1
    consul:
      loadbalancer:
        health-check:
          enabled: true
      host: localhost
      port: 8500
      discovery:
        register: true
        prefer-ip-address: true
        health-check-path: /actuator/health
        health-check-interval: 5s
server:
  port:
oci:
  config:
    namespace:
    bucket-name:
    compartment-id:
aws:
  config:
    bucket-name:
    sns-topic-arn:
    iam-role-arn:
gemini:
  config:
    api-key:
resilience4j:
  retry:
    instances:
      remoteCall:
        maxAttempts: 3
        waitDuration: 70ms
  circuitbreaker:
    instances:
      remoteCall:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10ms
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
  timelimiter:
    instances:
      remoteCall:
        timeoutDuration: 100ms
        cancelRunningFuture: true
axon:
  axonserver:
    servers:
  serializer:
    general: jackson
    events: jackson
    messages: jackson